2024-09-18 06:20:18 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}
2024-09-18 06:20:27 | INFO    | __main__:claim_epic_games:97 | Try to flush cookie - {'task': 'claim_epic_games'}
2024-09-18 06:20:29 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=Ea_P_9yQRMjbufCHTbSJS8s5oTEyltmw0H35Rk0jO80-1726611628-0.0.1.1-6676'}
2024-09-18 06:20:59 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 0}
2024-09-18 06:21:01 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=aoHOEhnLZocgYXH08oaL9xMknTrpcEDeL4j46tzPL2E-1726611660-0.0.1.1-6441'}
2024-09-18 06:21:31 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 1}
2024-09-18 06:21:32 | INFO    | epic_games.agent:_login:237 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games&__cf_chl_rt_tk=FvuGPWvdDVk1kw_v8Bevsj3e47L8Q.uP50Hz5HSGAZE-1726611692-0.0.1.1-6463'}
2024-09-18 06:22:02 | WARNING    | epic_games.agent:authorize:266 | 执行超时 - {'task': 'authorize', 'retry': 2}
2024-09-18 06:22:02 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3712), thread 'MainThread' (140189255445376): - {}
Traceback (most recent call last):
  File "/home/runner/work/epicfree/epicfree/epic/src/claim.py", line 162, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/home/runner/work/epicfree/epicfree/epic/src/claim.py", line 158, in run
    await agent.stash()
  File "/home/runner/work/epicfree/epicfree/epic/src/claim.py", line 151, in stash
    await self.claim_epic_games(context)
  File "/home/runner/work/epicfree/epicfree/epic/src/claim.py", line 98, in claim_epic_games
    if await epic.authorize(page):
  File "/home/runner/work/epicfree/epicfree/epic/src/epic_games/agent.py", line 269, in authorize
    raise RuntimeError(f"Failed to flush token - agent={self.__class__.__name__}")
RuntimeError: Failed to flush token - agent=EpicGames
